plugins:
  - jekyll-paginate-v2
  - jekyll-feed

pagination:
  enabled: true
  per_page: 10
  permalink: /page:num/
  sort_field: date
  sort_reverse: true

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: blog_default
      permalink: /posts/:title/
